window.LEXLOGICA_TOP100 = [
{rank:1,id:"mit",cdId:"mit",name:"Massachusetts Institute of Technology",short:"MIT",location:"Cambridge, MA",domain:"mit.edu"},
{rank:2,id:"columbia",cdId:"columbia",name:"Columbia University",short:"Columbia",location:"New York, NY",domain:"columbia.edu"},
{rank:3,id:"princeton",cdId:"princeton",name:"Princeton University",short:"Princeton",location:"Princeton, NJ",domain:"princeton.edu"},
{rank:4,id:"stanford",cdId:"stanford",name:"Stanford University",short:"Stanford",location:"Stanford, CA",domain:"stanford.edu"},
{rank:5,id:"uc-berkeley",cdId:"uc-berkeley",name:"University of California, Berkeley",short:"UC Berkeley",location:"Berkeley, CA",domain:"berkeley.edu"},
{rank:6,id:"harvard",cdId:"harvard",name:"Harvard University",short:"Harvard",location:"Cambridge, MA",domain:"harvard.edu"},
{rank:7,id:"williams",cdId:"williams-college",name:"Williams College",short:"Williams",location:"Williamstown, MA",domain:"williams.edu"},
{rank:8,id:"johns-hopkins",cdId:"johns-hopkins",name:"Johns Hopkins University",short:"Johns Hopkins",location:"Baltimore, MD",domain:"jhu.edu"},
{rank:9,id:"yale",cdId:"yale",name:"Yale University",short:"Yale",location:"New Haven, CT",domain:"yale.edu"},
{rank:10,id:"upenn",cdId:"university-of-pennsylvania",name:"University of Pennsylvania",short:"Penn",location:"Philadelphia, PA",domain:"upenn.edu"},
{rank:11,id:"vanderbilt",cdId:"vanderbilt",name:"Vanderbilt University",short:"Vanderbilt",location:"Nashville, TN",domain:"vanderbilt.edu"},
{rank:12,id:"rice",cdId:"rice",name:"Rice University",short:"Rice",location:"Houston, TX",domain:"rice.edu"},
{rank:13,id:"uchicago",cdId:"university-of-chicago",name:"University of Chicago",short:"UChicago",location:"Chicago, IL",domain:"uchicago.edu"},
{rank:14,id:"cornell",cdId:"cornell",name:"Cornell University",short:"Cornell",location:"Ithaca, NY",domain:"cornell.edu"},
{rank:15,id:"ucla",cdId:"ucla",name:"University of California, Los Angeles",short:"UCLA",location:"Los Angeles, CA",domain:"ucla.edu"},
{rank:16,id:"northwestern",cdId:"northwestern",name:"Northwestern University",short:"Northwestern",location:"Evanston, IL",domain:"northwestern.edu"},
{rank:17,id:"dartmouth",cdId:"dartmouth",name:"Dartmouth College",short:"Dartmouth",location:"Hanover, NH",domain:"dartmouth.edu"},
{rank:18,id:"brown",cdId:"brown",name:"Brown University",short:"Brown",location:"Providence, RI",domain:"brown.edu"},
{rank:19,id:"amherst",cdId:"amherst-college",name:"Amherst College",short:"Amherst",location:"Amherst, MA",domain:"amherst.edu"},
{rank:20,id:"ucsd",cdId:"university-of-california-san-diego",name:"University of California, San Diego",short:"UC San Diego",location:"La Jolla, CA",domain:"ucsd.edu"},
{rank:21,id:"michigan",cdId:"university-of-michigan-ann-arbor",name:"University of Michigan, Ann Arbor",short:"Michigan",location:"Ann Arbor, MI",domain:"umich.edu"},
{rank:22,id:"duke",cdId:"duke",name:"Duke University",short:"Duke",location:"Durham, NC",domain:"duke.edu"},
{rank:23,id:"swarthmore",cdId:"swarthmore-college",name:"Swarthmore College",short:"Swarthmore",location:"Swarthmore, PA",domain:"swarthmore.edu"},
{rank:24,id:"caltech",cdId:"caltech",name:"California Institute of Technology",short:"Caltech",location:"Pasadena, CA",domain:"caltech.edu"},
{rank:25,id:"washu",cdId:"washington-university-in-st-louis",name:"Washington University in St. Louis",short:"WashU",location:"St. Louis, MO",domain:"wustl.edu"},
{rank:26,id:"claremont-mckenna",cdId:"claremont-mckenna-college",name:"Claremont McKenna College",short:"Claremont McKenna",location:"Claremont, CA",domain:"cmc.edu"},
{rank:27,id:"emory",cdId:"emory",name:"Emory University",short:"Emory",location:"Atlanta, GA",domain:"emory.edu"},
{rank:28,id:"usc",cdId:"university-of-southern-california",name:"University of Southern California",short:"USC",location:"Los Angeles, CA",domain:"usc.edu"},
{rank:29,id:"wellesley",cdId:"wellesley-college",name:"Wellesley College",short:"Wellesley",location:"Wellesley, MA",domain:"wellesley.edu"},
{rank:30,id:"florida",cdId:"university-of-florida",name:"University of Florida",short:"Florida",location:"Gainesville, FL",domain:"ufl.edu"},
{rank:31,id:"uc-irvine",cdId:"university-of-california-irvine",name:"University of California, Irvine",short:"UC Irvine",location:"Irvine, CA",domain:"uci.edu"},
{rank:32,id:"georgia-tech",cdId:"georgia-tech",name:"Georgia Institute of Technology",short:"Georgia Tech",location:"Atlanta, GA",domain:"gatech.edu"},
{rank:33,id:"notre-dame",cdId:"university-of-notre-dame",name:"University of Notre Dame",short:"Notre Dame",location:"Notre Dame, IN",domain:"nd.edu"},
{rank:34,id:"uva",cdId:"university-of-virginia",name:"University of Virginia",short:"Virginia",location:"Charlottesville, VA",domain:"virginia.edu"},
{rank:35,id:"unc",cdId:"university-of-north-carolina-chapel-hill",name:"University of North Carolina at Chapel Hill",short:"UNC",location:"Chapel Hill, NC",domain:"unc.edu"},
{rank:36,id:"pomona",cdId:"pomona-college",name:"Pomona College",short:"Pomona",location:"Claremont, CA",domain:"pomona.edu"},
{rank:37,id:"umd",cdId:"umd",name:"University of Maryland, College Park",short:"Maryland",location:"College Park, MD",domain:"umd.edu"},
{rank:38,id:"uiuc",cdId:"university-of-illinois-urbana-champaign",name:"University of Illinois Urbana-Champaign",short:"UIUC",location:"Champaign, IL",domain:"illinois.edu"},
{rank:39,id:"bowdoin",cdId:"bowdoin",name:"Bowdoin College",short:"Bowdoin",location:"Brunswick, ME",domain:"bowdoin.edu"},
{rank:40,id:"byu",cdId:"brigham-young-university",name:"Brigham Young University",short:"BYU",location:"Provo, UT",domain:"byu.edu"},
{rank:41,id:"georgetown",cdId:"georgetown",name:"Georgetown University",short:"Georgetown",location:"Washington, DC",domain:"georgetown.edu"},
{rank:42,id:"ucsb",cdId:"uc-santa-barbara",name:"University of California, Santa Barbara",short:"UC Santa Barbara",location:"Santa Barbara, CA",domain:"ucsb.edu"},
{rank:43,id:"cmu",cdId:"carnegie-mellon",name:"Carnegie Mellon University",short:"Carnegie Mellon",location:"Pittsburgh, PA",domain:"cmu.edu"},
{rank:44,id:"uc-davis",cdId:"uc-davis",name:"University of California, Davis",short:"UC Davis",location:"Davis, CA",domain:"ucdavis.edu"},
{rank:45,id:"boston-university",cdId:"boston-university",name:"Boston University",short:"Boston University",location:"Boston, MA",domain:"bu.edu"},
{rank:46,id:"ut-austin",cdId:"university-of-texas-at-austin",name:"University of Texas at Austin",short:"UT Austin",location:"Austin, TX",domain:"utexas.edu"},
{rank:47,id:"washington-lee",cdId:"washington-and-lee-university",name:"Washington and Lee University",short:"Washington and Lee",location:"Lexington, VA",domain:"wlu.edu"},
{rank:48,id:"colgate",cdId:"colgate-university",name:"Colgate University",short:"Colgate",location:"Hamilton, NY",domain:"colgate.edu"},
{rank:49,id:"nyu",cdId:"new-york-university",name:"New York University",short:"NYU",location:"New York, NY",domain:"nyu.edu"},
{rank:50,id:"uw-seattle",cdId:"university-of-washington",name:"University of Washington, Seattle",short:"Washington",location:"Seattle, WA",domain:"washington.edu"},
{rank:51,id:"wesleyan",cdId:"wesleyan-university",name:"Wesleyan University",short:"Wesleyan",location:"Middletown, CT",domain:"wesleyan.edu"},
{rank:52,id:"middlebury",cdId:"middlebury-college",name:"Middlebury College",short:"Middlebury",location:"Middlebury, VT",domain:"middlebury.edu"},
{rank:53,id:"wisconsin",cdId:"university-of-wisconsin-madison",name:"University of Wisconsin–Madison",short:"Wisconsin",location:"Madison, WI",domain:"wisc.edu"},
{rank:54,id:"boston-college",cdId:"boston-college",name:"Boston College",short:"Boston College",location:"Chestnut Hill, MA",domain:"bc.edu"},
{rank:55,id:"cal-poly",cdId:"california-polytechnic-state-university-san-luis-obispo",name:"California Polytechnic State University, San Luis Obispo",short:"Cal Poly",location:"San Luis Obispo, CA",domain:"calpoly.edu"},
{rank:56,id:"haverford",cdId:"haverford-college",name:"Haverford College",short:"Haverford",location:"Haverford, PA",domain:"haverford.edu"},
{rank:57,id:"uga",cdId:"university-of-georgia",name:"University of Georgia",short:"Georgia",location:"Athens, GA",domain:"uga.edu"},
{rank:58,id:"tufts",cdId:"tufts",name:"Tufts University",short:"Tufts",location:"Medford, MA",domain:"tufts.edu"},
{rank:59,id:"davidson",cdId:"davidson-college",name:"Davidson College",short:"Davidson",location:"Davidson, NC",domain:"davidson.edu"},
{rank:60,id:"william-mary",cdId:"william-and-mary",name:"William & Mary",short:"William & Mary",location:"Williamsburg, VA",domain:"wm.edu"},
{rank:61,id:"texas-am",cdId:"texas-am-university",name:"Texas A&M University, College Station",short:"Texas A&M",location:"College Station, TX",domain:"tamu.edu"},
{rank:62,id:"purdue",cdId:"purdue-university",name:"Purdue University",short:"Purdue",location:"West Lafayette, IN",domain:"purdue.edu"},
{rank:63,id:"ucsc",cdId:"university-of-california-santa-cruz",name:"University of California, Santa Cruz",short:"UC Santa Cruz",location:"Santa Cruz, CA",domain:"ucsc.edu"},
{rank:64,id:"lehigh",cdId:"lehigh-university",name:"Lehigh University",short:"Lehigh",location:"Bethlehem, PA",domain:"lehigh.edu"},
{rank:65,id:"santa-clara",cdId:"santa-clara-university",name:"Santa Clara University",short:"Santa Clara",location:"Santa Clara, CA",domain:"scu.edu"},
{rank:66,id:"nc-state",cdId:"north-carolina-state-university",name:"North Carolina State University, Raleigh",short:"NC State",location:"Raleigh, NC",domain:"ncsu.edu"},
{rank:67,id:"gwu",cdId:"gwu",name:"George Washington University",short:"GWU",location:"Washington, DC",domain:"gwu.edu"},
{rank:68,id:"binghamton",cdId:"binghamton-university",name:"Binghamton University, SUNY",short:"Binghamton",location:"Vestal, NY",domain:"binghamton.edu"},
{rank:69,id:"rochester",cdId:"university-of-rochester",name:"University of Rochester",short:"Rochester",location:"Rochester, NY",domain:"rochester.edu"},
{rank:70,id:"rutgers",cdId:"rutgers-university-new-brunswick",name:"Rutgers University–New Brunswick",short:"Rutgers",location:"New Brunswick, NJ",domain:"rutgers.edu"},
{rank:71,id:"colby",cdId:"colby-college",name:"Colby College",short:"Colby",location:"Waterville, ME",domain:"colby.edu"},
{rank:72,id:"fsu",cdId:"florida-state-university",name:"Florida State University",short:"Florida State",location:"Tallahassee, FL",domain:"fsu.edu"},
{rank:73,id:"hamilton",cdId:"hamilton-college",name:"Hamilton College",short:"Hamilton",location:"Clinton, NY",domain:"hamilton.edu"},
{rank:74,id:"holy-cross",cdId:"college-of-the-holy-cross",name:"College of the Holy Cross",short:"Holy Cross",location:"Worcester, MA",domain:"holycross.edu"},
{rank:75,id:"villanova",cdId:"villanova-university",name:"Villanova University",short:"Villanova",location:"Villanova, PA",domain:"villanova.edu"},
{rank:76,id:"miami",cdId:"university-of-miami",name:"University of Miami",short:"Miami",location:"Coral Gables, FL",domain:"miami.edu"},
{rank:77,id:"ucr",cdId:"university-of-california-riverside",name:"University of California, Riverside",short:"UC Riverside",location:"Riverside, CA",domain:"ucr.edu"},
{rank:78,id:"minnesota",cdId:"university-of-minnesota-twin-cities",name:"University of Minnesota, Twin Cities",short:"Minnesota",location:"Minneapolis, MN",domain:"umn.edu"},
{rank:79,id:"michigan-state",cdId:"michigan-state-university",name:"Michigan State University",short:"Michigan State",location:"East Lansing, MI",domain:"msu.edu"},
{rank:80,id:"stony-brook",cdId:"stony-brook-university",name:"Stony Brook University, SUNY",short:"Stony Brook",location:"Stony Brook, NY",domain:"stonybrook.edu"},
{rank:81,id:"virginia-tech",cdId:"virginia-tech",name:"Virginia Tech",short:"Virginia Tech",location:"Blacksburg, VA",domain:"vt.edu"},
{rank:82,id:"trinity-tx",cdId:"trinity-university",name:"Trinity University",short:"Trinity",location:"San Antonio, TX",domain:"trinity.edu"},
{rank:83,id:"ohio-state",cdId:"ohio-state-university",name:"Ohio State University",short:"Ohio State",location:"Columbus, OH",domain:"osu.edu"},
{rank:84,id:"harvey-mudd",cdId:"harvey-mudd-college",name:"Harvey Mudd College",short:"Harvey Mudd",location:"Claremont, CA",domain:"hmc.edu"},
{rank:85,id:"bucknell",cdId:"bucknell-university",name:"Bucknell University",short:"Bucknell",location:"Lewisburg, PA",domain:"bucknell.edu"},
{rank:86,id:"clemson",cdId:"clemson-university",name:"Clemson University",short:"Clemson",location:"Clemson, SC",domain:"clemson.edu"},
{rank:87,id:"sdsu",cdId:"san-diego-state-university",name:"San Diego State University",short:"San Diego State",location:"San Diego, CA",domain:"sdsu.edu"},
{rank:88,id:"trinity-ct",cdId:"trinity-college",name:"Trinity College",short:"Trinity College",location:"Hartford, CT",domain:"trincoll.edu"},
{rank:89,id:"smith",cdId:"smith-college",name:"Smith College",short:"Smith",location:"Northampton, MA",domain:"smith.edu"},
{rank:90,id:"baruch",cdId:"baruch-college",name:"CUNY, Baruch College",short:"Baruch",location:"New York, NY",domain:"baruch.cuny.edu"},
{rank:91,id:"lafayette",cdId:"lafayette-college",name:"Lafayette College",short:"Lafayette",location:"Easton, PA",domain:"lafayette.edu"},
{rank:92,id:"richmond",cdId:"university-of-richmond",name:"University of Richmond",short:"Richmond",location:"Richmond, VA",domain:"richmond.edu"},
{rank:93,id:"colorado",cdId:"colorado",name:"University of Colorado Boulder",short:"Colorado",location:"Boulder, CO",domain:"colorado.edu"},
{rank:94,id:"indiana",cdId:"indiana-university-bloomington",name:"Indiana University Bloomington",short:"Indiana",location:"Bloomington, IN",domain:"indiana.edu"},
{rank:95,id:"babson",cdId:"babson-college",name:"Babson College",short:"Babson",location:"Wellesley, MA",domain:"babson.edu"},
{rank:96,id:"oklahoma",cdId:"university-of-oklahoma",name:"University of Oklahoma, Norman",short:"Oklahoma",location:"Norman, OK",domain:"ou.edu"},
{rank:97,id:"csulb",cdId:"california-state-university-long-beach",name:"California State University, Long Beach",short:"Cal State Long Beach",location:"Long Beach, CA",domain:"csulb.edu"},
{rank:98,id:"wake-forest",cdId:"wake-forest-university",name:"Wake Forest University",short:"Wake Forest",location:"Winston-Salem, NC",domain:"wfu.edu"},
{rank:99,id:"utah",cdId:"university-of-utah",name:"University of Utah",short:"Utah",location:"Salt Lake City, UT",domain:"utah.edu"},
{rank:100,id:"bates",cdId:"bates-college",name:"Bates College",short:"Bates",location:"Lewiston, ME",domain:"bates.edu"},
{"rank":101,"id":"barnard","cdId":"barnard-college","name":"Barnard College","short":"Barnard","location":"New York, NY","domain":"barnard.edu"},
{"rank":102,"id":"carleton","cdId":"carleton-college","name":"Carleton College","short":"Carleton","location":"Northfield, MN","domain":"carleton.edu"},
{"rank":103,"id":"grinnell","cdId":"grinnell-college","name":"Grinnell College","short":"Grinnell","location":"Grinnell, IA","domain":"grinnell.edu"},
{"rank":104,"id":"vassar","cdId":"vassar-college","name":"Vassar College","short":"Vassar","location":"Poughkeepsie, NY","domain":"vassar.edu"},
{"rank":105,"id":"macalester","cdId":"macalester-college","name":"Macalester College","short":"Macalester","location":"Saint Paul, MN","domain":"macalester.edu"},
{"rank":106,"id":"oberlin","cdId":"oberlin-college","name":"Oberlin College","short":"Oberlin","location":"Oberlin, OH","domain":"oberlin.edu"},
{"rank":107,"id":"kenyon","cdId":"kenyon-college","name":"Kenyon College","short":"Kenyon","location":"Gambier, OH","domain":"kenyon.edu"},
{"rank":108,"id":"colorado-college","cdId":"colorado-college","name":"Colorado College","short":"Colorado College","location":"Colorado Springs, CO","domain":"coloradocollege.edu"},
{"rank":109,"id":"usna","cdId":"united-states-naval-academy","name":"United States Naval Academy","short":"Naval Academy","location":"Annapolis, MD","domain":"usna.edu"},
{"rank":110,"id":"west-point","cdId":"united-states-military-academy","name":"United States Military Academy","short":"West Point","location":"West Point, NY","domain":"westpoint.edu"},
{"rank":111,"id":"usafa","cdId":"united-states-air-force-academy","name":"United States Air Force Academy","short":"Air Force Academy","location":"Colorado Springs, CO","domain":"usafa.edu"},
{"rank":112,"id":"northeastern","cdId":"northeastern-university","name":"Northeastern University","short":"Northeastern","location":"Boston, MA","domain":"northeastern.edu"},
{"rank":113,"id":"tulane","cdId":"tulane-university","name":"Tulane University","short":"Tulane","location":"New Orleans, LA","domain":"tulane.edu"},
{"rank":114,"id":"case-western","cdId":"case-western-reserve-university","name":"Case Western Reserve University","short":"Case Western","location":"Cleveland, OH","domain":"case.edu"},
{"rank":115,"id":"syracuse","cdId":"syracuse-university","name":"Syracuse University","short":"Syracuse","location":"Syracuse, NY","domain":"syr.edu"},
{"rank":116,"id":"penn-state","cdId":"pennsylvania-state-university","name":"Pennsylvania State University","short":"Penn State","location":"University Park, PA","domain":"psu.edu"},
{"rank":117,"id":"uconn","cdId":"university-of-connecticut","name":"University of Connecticut","short":"UConn","location":"Storrs, CT","domain":"uconn.edu"},
{"rank":118,"id":"rpi","cdId":"rensselaer-polytechnic-institute","name":"Rensselaer Polytechnic Institute","short":"RPI","location":"Troy, NY","domain":"rpi.edu"},
{"rank":119,"id":"stevens","cdId":"stevens-institute-of-technology","name":"Stevens Institute of Technology","short":"Stevens","location":"Hoboken, NJ","domain":"stevens.edu"},
{"rank":120,"id":"wpi","cdId":"worcester-polytechnic-institute","name":"Worcester Polytechnic Institute","short":"WPI","location":"Worcester, MA","domain":"wpi.edu"},
{"rank":121,"id":"reed","cdId":"reed-college","name":"Reed College","short":"Reed","location":"Portland, OR","domain":"reed.edu"},
{"rank":122,"id":"denison","cdId":"denison-university","name":"Denison University","short":"Denison","location":"Granville, OH","domain":"denison.edu"},
{"rank":123,"id":"occidental","cdId":"occidental-college","name":"Occidental College","short":"Occidental","location":"Los Angeles, CA","domain":"oxy.edu"},
{"rank":124,"id":"skidmore","cdId":"skidmore-college","name":"Skidmore College","short":"Skidmore","location":"Saratoga Springs, NY","domain":"skidmore.edu"},
{"rank":125,"id":"bryn-mawr","cdId":"bryn-mawr-college","name":"Bryn Mawr College","short":"Bryn Mawr","location":"Bryn Mawr, PA","domain":"brynmawr.edu"},
{"rank":126,"id":"mount-holyoke","cdId":"mount-holyoke-college","name":"Mount Holyoke College","short":"Mount Holyoke","location":"South Hadley, MA","domain":"mtholyoke.edu"},
{"rank":127,"id":"pittsburgh","cdId":"university-of-pittsburgh","name":"University of Pittsburgh","short":"Pitt","location":"Pittsburgh, PA","domain":"pitt.edu"},
{"rank":128,"id":"iowa","cdId":"university-of-iowa","name":"University of Iowa","short":"Iowa","location":"Iowa City, IA","domain":"uiowa.edu"},
{"rank":129,"id":"delaware","cdId":"university-of-delaware","name":"University of Delaware","short":"Delaware","location":"Newark, DE","domain":"udel.edu"},
{"rank":130,"id":"tennessee","cdId":"university-of-tennessee-knoxville","name":"University of Tennessee, Knoxville","short":"Tennessee","location":"Knoxville, TN","domain":"utk.edu"},
{"rank":131,"id":"south-carolina","cdId":"university-of-south-carolina","name":"University of South Carolina","short":"South Carolina","location":"Columbia, SC","domain":"sc.edu"},
{"rank":132,"id":"asu","cdId":"arizona-state-university","name":"Arizona State University","short":"Arizona State","location":"Tempe, AZ","domain":"asu.edu"},
{"rank":133,"id":"arizona","cdId":"university-of-arizona","name":"University of Arizona","short":"Arizona","location":"Tucson, AZ","domain":"arizona.edu"},
{"rank":134,"id":"oregon","cdId":"university-of-oregon","name":"University of Oregon","short":"Oregon","location":"Eugene, OR","domain":"uoregon.edu"},
{"rank":135,"id":"fordham","cdId":"fordham-university","name":"Fordham University","short":"Fordham","location":"New York, NY","domain":"fordham.edu"},
{"rank":136,"id":"baylor","cdId":"baylor-university","name":"Baylor University","short":"Baylor","location":"Waco, TX","domain":"baylor.edu"},
{"rank":137,"id":"tcu","cdId":"texas-christian-university","name":"Texas Christian University","short":"TCU","location":"Fort Worth, TX","domain":"tcu.edu"},
{"rank":138,"id":"smu","cdId":"southern-methodist-university","name":"Southern Methodist University","short":"SMU","location":"Dallas, TX","domain":"smu.edu"},
{"rank":139,"id":"pepperdine","cdId":"pepperdine-university","name":"Pepperdine University","short":"Pepperdine","location":"Malibu, CA","domain":"pepperdine.edu"},
{"rank":140,"id":"loyola-marymount","cdId":"loyola-marymount-university","name":"Loyola Marymount University","short":"Loyola Marymount","location":"Los Angeles, CA","domain":"lmu.edu"},
{"rank":141,"id":"gonzaga","cdId":"gonzaga-university","name":"Gonzaga University","short":"Gonzaga","location":"Spokane, WA","domain":"gonzaga.edu"},
{"rank":142,"id":"howard","cdId":"howard-university","name":"Howard University","short":"Howard","location":"Washington, DC","domain":"howard.edu"},
{"rank":143,"id":"spelman","cdId":"spelman-college","name":"Spelman College","short":"Spelman","location":"Atlanta, GA","domain":"spelman.edu"},
{"rank":144,"id":"morehouse","cdId":"morehouse-college","name":"Morehouse College","short":"Morehouse","location":"Atlanta, GA","domain":"morehouse.edu"},
{"rank":145,"id":"american","cdId":"american-university","name":"American University","short":"American","location":"Washington, DC","domain":"american.edu"},
{"rank":146,"id":"brandeis","cdId":"brandeis-university","name":"Brandeis University","short":"Brandeis","location":"Waltham, MA","domain":"brandeis.edu"},
{"rank":147,"id":"yeshiva","cdId":"yeshiva-university","name":"Yeshiva University","short":"Yeshiva","location":"New York, NY","domain":"yu.edu"},
{"rank":148,"id":"rit","cdId":"rochester-institute-of-technology","name":"Rochester Institute of Technology","short":"RIT","location":"Rochester, NY","domain":"rit.edu"},
{"rank":149,"id":"drexel","cdId":"drexel-university","name":"Drexel University","short":"Drexel","location":"Philadelphia, PA","domain":"drexel.edu"},
{"rank":150,"id":"temple","cdId":"temple-university","name":"Temple University","short":"Temple","location":"Philadelphia, PA","domain":"temple.edu"},
{"rank":151,"id":"loyola-chicago","cdId":"loyola-university-chicago","name":"Loyola University Chicago","short":"Loyola Chicago","location":"Chicago, IL","domain":"luc.edu"},
{"rank":152,"id":"depaul","cdId":"depaul-university","name":"DePaul University","short":"DePaul","location":"Chicago, IL","domain":"depaul.edu"},
{"rank":153,"id":"marquette","cdId":"marquette-university","name":"Marquette University","short":"Marquette","location":"Milwaukee, WI","domain":"marquette.edu"},
{"rank":154,"id":"miami-ohio","cdId":"miami-university","name":"Miami University","short":"Miami (Ohio)","location":"Oxford, OH","domain":"miamioh.edu"},
{"rank":155,"id":"iowa-state","cdId":"iowa-state-university","name":"Iowa State University","short":"Iowa State","location":"Ames, IA","domain":"iastate.edu"},
{"rank":156,"id":"kansas","cdId":"university-of-kansas","name":"University of Kansas","short":"Kansas","location":"Lawrence, KS","domain":"ku.edu"},
{"rank":157,"id":"nebraska","cdId":"university-of-nebraska-lincoln","name":"University of Nebraska–Lincoln","short":"Nebraska","location":"Lincoln, NE","domain":"unl.edu"},
{"rank":158,"id":"missouri","cdId":"university-of-missouri","name":"University of Missouri","short":"Missouri","location":"Columbia, MO","domain":"missouri.edu"},
{"rank":159,"id":"auburn","cdId":"auburn-university","name":"Auburn University","short":"Auburn","location":"Auburn, AL","domain":"auburn.edu"},
{"rank":160,"id":"alabama","cdId":"university-of-alabama","name":"University of Alabama","short":"Alabama","location":"Tuscaloosa, AL","domain":"ua.edu"},
{"rank":161,"id":"arkansas","cdId":"university-of-arkansas","name":"University of Arkansas","short":"Arkansas","location":"Fayetteville, AR","domain":"uark.edu"},
{"rank":162,"id":"kentucky","cdId":"university-of-kentucky","name":"University of Kentucky","short":"Kentucky","location":"Lexington, KY","domain":"uky.edu"},
{"rank":163,"id":"louisville","cdId":"university-of-louisville","name":"University of Louisville","short":"Louisville","location":"Louisville, KY","domain":"louisville.edu"},
{"rank":164,"id":"oregon-state","cdId":"oregon-state-university","name":"Oregon State University","short":"Oregon State","location":"Corvallis, OR","domain":"oregonstate.edu"},
{"rank":165,"id":"washington-state","cdId":"washington-state-university","name":"Washington State University","short":"Washington State","location":"Pullman, WA","domain":"wsu.edu"},
{"rank":166,"id":"colorado-state","cdId":"colorado-state-university","name":"Colorado State University","short":"Colorado State","location":"Fort Collins, CO","domain":"colostate.edu"},
{"rank":167,"id":"uc-merced","cdId":"university-of-california-merced","name":"University of California, Merced","short":"UC Merced","location":"Merced, CA","domain":"ucmerced.edu"},
{"rank":168,"id":"umass-amherst","cdId":"university-of-massachusetts-amherst","name":"University of Massachusetts Amherst","short":"UMass Amherst","location":"Amherst, MA","domain":"umass.edu"},
{"rank":169,"id":"buffalo","cdId":"university-at-buffalo","name":"University at Buffalo, SUNY","short":"Buffalo","location":"Buffalo, NY","domain":"buffalo.edu"},
{"rank":170,"id":"albany","cdId":"university-at-albany-suny","name":"University at Albany, SUNY","short":"UAlbany","location":"Albany, NY","domain":"albany.edu"},
{"rank":171,"id":"vermont","cdId":"university-of-vermont","name":"University of Vermont","short":"Vermont","location":"Burlington, VT","domain":"uvm.edu"},
{"rank":172,"id":"new-hampshire","cdId":"university-of-new-hampshire","name":"University of New Hampshire","short":"New Hampshire","location":"Durham, NH","domain":"unh.edu"},
{"rank":173,"id":"george-mason","cdId":"george-mason-university","name":"George Mason University","short":"George Mason","location":"Fairfax, VA","domain":"gmu.edu"},
{"rank":174,"id":"ucf","cdId":"university-of-central-florida","name":"University of Central Florida","short":"UCF","location":"Orlando, FL","domain":"ucf.edu"},
{"rank":175,"id":"usf","cdId":"university-of-south-florida","name":"University of South Florida","short":"USF","location":"Tampa, FL","domain":"usf.edu"},
{"rank":176,"id":"fiu","cdId":"florida-international-university","name":"Florida International University","short":"FIU","location":"Miami, FL","domain":"fiu.edu"},
{"rank":177,"id":"cincinnati","cdId":"university-of-cincinnati","name":"University of Cincinnati","short":"Cincinnati","location":"Cincinnati, OH","domain":"uc.edu"},
{"rank":178,"id":"houston","cdId":"university-of-houston","name":"University of Houston","short":"Houston","location":"Houston, TX","domain":"uh.edu"},
{"rank":179,"id":"ut-dallas","cdId":"university-of-texas-at-dallas","name":"University of Texas at Dallas","short":"UT Dallas","location":"Richardson, TX","domain":"utdallas.edu"},
{"rank":180,"id":"ut-arlington","cdId":"university-of-texas-at-arlington","name":"University of Texas at Arlington","short":"UT Arlington","location":"Arlington, TX","domain":"uta.edu"},
{"rank":181,"id":"denver","cdId":"university-of-denver","name":"University of Denver","short":"Denver","location":"Denver, CO","domain":"du.edu"},
{"rank":182,"id":"creighton","cdId":"creighton-university","name":"Creighton University","short":"Creighton","location":"Omaha, NE","domain":"creighton.edu"},
{"rank":183,"id":"saint-louis","cdId":"saint-louis-university","name":"Saint Louis University","short":"Saint Louis","location":"St. Louis, MO","domain":"slu.edu"},
{"rank":184,"id":"chapman","cdId":"chapman-university","name":"Chapman University","short":"Chapman","location":"Orange, CA","domain":"chapman.edu"},
{"rank":185,"id":"san-diego","cdId":"university-of-san-diego","name":"University of San Diego","short":"San Diego","location":"San Diego, CA","domain":"sandiego.edu"},
{"rank":186,"id":"cooper-union","cdId":"cooper-union","name":"The Cooper Union","short":"Cooper Union","location":"New York, NY","domain":"cooper.edu"},
{"rank":187,"id":"olin","cdId":"olin-college","name":"Franklin W. Olin College of Engineering","short":"Olin","location":"Needham, MA","domain":"olin.edu"},
{"rank":188,"id":"rose-hulman","cdId":"rose-hulman-institute-of-technology","name":"Rose-Hulman Institute of Technology","short":"Rose-Hulman","location":"Terre Haute, IN","domain":"rose-hulman.edu"},
{"rank":189,"id":"pitzer","cdId":"pitzer-college","name":"Pitzer College","short":"Pitzer","location":"Claremont, CA","domain":"pitzer.edu"},
{"rank":190,"id":"scripps","cdId":"scripps-college","name":"Scripps College","short":"Scripps","location":"Claremont, CA","domain":"scrippscollege.edu"},
{"rank":191,"id":"franklin-marshall","cdId":"franklin-and-marshall-college","name":"Franklin & Marshall College","short":"Franklin & Marshall","location":"Lancaster, PA","domain":"fandm.edu"},
{"rank":192,"id":"gettysburg","cdId":"gettysburg-college","name":"Gettysburg College","short":"Gettysburg","location":"Gettysburg, PA","domain":"gettysburg.edu"},
{"rank":193,"id":"dickinson","cdId":"dickinson-college","name":"Dickinson College","short":"Dickinson","location":"Carlisle, PA","domain":"dickinson.edu"},
{"rank":194,"id":"union","cdId":"union-college","name":"Union College","short":"Union","location":"Schenectady, NY","domain":"union.edu"},
{"rank":195,"id":"st-olaf","cdId":"st-olaf-college","name":"St. Olaf College","short":"St. Olaf","location":"Northfield, MN","domain":"stolaf.edu"},
{"rank":196,"id":"furman","cdId":"furman-university","name":"Furman University","short":"Furman","location":"Greenville, SC","domain":"furman.edu"},
{"rank":197,"id":"rhodes","cdId":"rhodes-college","name":"Rhodes College","short":"Rhodes","location":"Memphis, TN","domain":"rhodes.edu"},
{"rank":198,"id":"sewanee","cdId":"sewanee-the-university-of-the-south","name":"Sewanee: The University of the South","short":"Sewanee","location":"Sewanee, TN","domain":"sewanee.edu"},
{"rank":199,"id":"whitman","cdId":"whitman-college","name":"Whitman College","short":"Whitman","location":"Walla Walla, WA","domain":"whitman.edu"},
{"rank":200,"id":"connecticut-college","cdId":"connecticut-college","name":"Connecticut College","short":"Connecticut College","location":"New London, CT","domain":"conncoll.edu"}
];
