window.LEXLOGICA_TOP100 = [
{rank:1,id:"mit",cdId:"mit",name:"Massachusetts Institute of Technology",short:"MIT",location:"Cambridge, MA",domain:"mit.edu"},
{rank:2,id:"columbia",cdId:"columbia",name:"Columbia University",short:"Columbia",location:"New York, NY",domain:"columbia.edu"},
{rank:3,id:"princeton",cdId:"princeton",name:"Princeton University",short:"Princeton",location:"Princeton, NJ",domain:"princeton.edu"},
{rank:4,id:"stanford",cdId:"stanford",name:"Stanford University",short:"Stanford",location:"Stanford, CA",domain:"stanford.edu"},
{rank:5,id:"uc-berkeley",cdId:"uc-berkeley",name:"University of California, Berkeley",short:"UC Berkeley",location:"Berkeley, CA",domain:"berkeley.edu"},
{rank:6,id:"harvard",cdId:"harvard",name:"Harvard University",short:"Harvard",location:"Cambridge, MA",domain:"harvard.edu"},
{rank:7,id:"williams",cdId:"williams-college",name:"Williams College",short:"Williams",location:"Williamstown, MA",domain:"williams.edu"},
{rank:8,id:"johns-hopkins",cdId:"johns-hopkins",name:"Johns Hopkins University",short:"Johns Hopkins",location:"Baltimore, MD",domain:"jhu.edu"},
{rank:9,id:"yale",cdId:"yale",name:"Yale University",short:"Yale",location:"New Haven, CT",domain:"yale.edu"},
{rank:10,id:"upenn",cdId:"university-of-pennsylvania",name:"University of Pennsylvania",short:"Penn",location:"Philadelphia, PA",domain:"upenn.edu"},
{rank:11,id:"vanderbilt",cdId:"vanderbilt",name:"Vanderbilt University",short:"Vanderbilt",location:"Nashville, TN",domain:"vanderbilt.edu"},
{rank:12,id:"rice",cdId:"rice",name:"Rice University",short:"Rice",location:"Houston, TX",domain:"rice.edu"},
{rank:13,id:"uchicago",cdId:"university-of-chicago",name:"University of Chicago",short:"UChicago",location:"Chicago, IL",domain:"uchicago.edu"},
{rank:14,id:"cornell",cdId:"cornell",name:"Cornell University",short:"Cornell",location:"Ithaca, NY",domain:"cornell.edu"},
{rank:15,id:"ucla",cdId:"ucla",name:"University of California, Los Angeles",short:"UCLA",location:"Los Angeles, CA",domain:"ucla.edu"},
{rank:16,id:"northwestern",cdId:"northwestern",name:"Northwestern University",short:"Northwestern",location:"Evanston, IL",domain:"northwestern.edu"},
{rank:17,id:"dartmouth",cdId:"dartmouth",name:"Dartmouth College",short:"Dartmouth",location:"Hanover, NH",domain:"dartmouth.edu"},
{rank:18,id:"brown",cdId:"brown",name:"Brown University",short:"Brown",location:"Providence, RI",domain:"brown.edu"},
{rank:19,id:"amherst",cdId:"amherst-college",name:"Amherst College",short:"Amherst",location:"Amherst, MA",domain:"amherst.edu"},
{rank:20,id:"ucsd",cdId:"university-of-california-san-diego",name:"University of California, San Diego",short:"UC San Diego",location:"La Jolla, CA",domain:"ucsd.edu"},
{rank:21,id:"michigan",cdId:"university-of-michigan-ann-arbor",name:"University of Michigan, Ann Arbor",short:"Michigan",location:"Ann Arbor, MI",domain:"umich.edu"},
{rank:22,id:"duke",cdId:"duke",name:"Duke University",short:"Duke",location:"Durham, NC",domain:"duke.edu"},
{rank:23,id:"swarthmore",cdId:"swarthmore-college",name:"Swarthmore College",short:"Swarthmore",location:"Swarthmore, PA",domain:"swarthmore.edu"},
{rank:24,id:"caltech",cdId:"caltech",name:"California Institute of Technology",short:"Caltech",location:"Pasadena, CA",domain:"caltech.edu"},
{rank:25,id:"washu",cdId:"washington-university-in-st-louis",name:"Washington University in St. Louis",short:"WashU",location:"St. Louis, MO",domain:"wustl.edu"},
{rank:26,id:"claremont-mckenna",cdId:"claremont-mckenna-college",name:"Claremont McKenna College",short:"Claremont McKenna",location:"Claremont, CA",domain:"cmc.edu"},
{rank:27,id:"emory",cdId:"emory",name:"Emory University",short:"Emory",location:"Atlanta, GA",domain:"emory.edu"},
{rank:28,id:"usc",cdId:"university-of-southern-california",name:"University of Southern California",short:"USC",location:"Los Angeles, CA",domain:"usc.edu"},
{rank:29,id:"wellesley",cdId:"wellesley-college",name:"Wellesley College",short:"Wellesley",location:"Wellesley, MA",domain:"wellesley.edu"},
{rank:30,id:"florida",cdId:"university-of-florida",name:"University of Florida",short:"Florida",location:"Gainesville, FL",domain:"ufl.edu"},
{rank:31,id:"uc-irvine",cdId:"university-of-california-irvine",name:"University of California, Irvine",short:"UC Irvine",location:"Irvine, CA",domain:"uci.edu"},
{rank:32,id:"georgia-tech",cdId:"georgia-tech",name:"Georgia Institute of Technology",short:"Georgia Tech",location:"Atlanta, GA",domain:"gatech.edu"},
{rank:33,id:"notre-dame",cdId:"university-of-notre-dame",name:"University of Notre Dame",short:"Notre Dame",location:"Notre Dame, IN",domain:"nd.edu"},
{rank:34,id:"uva",cdId:"university-of-virginia",name:"University of Virginia",short:"Virginia",location:"Charlottesville, VA",domain:"virginia.edu"},
{rank:35,id:"unc",cdId:"university-of-north-carolina-chapel-hill",name:"University of North Carolina at Chapel Hill",short:"UNC",location:"Chapel Hill, NC",domain:"unc.edu"},
{rank:36,id:"pomona",cdId:"pomona-college",name:"Pomona College",short:"Pomona",location:"Claremont, CA",domain:"pomona.edu"},
{rank:37,id:"umd",cdId:"umd",name:"University of Maryland, College Park",short:"Maryland",location:"College Park, MD",domain:"umd.edu"},
{rank:38,id:"uiuc",cdId:"university-of-illinois-urbana-champaign",name:"University of Illinois Urbana-Champaign",short:"UIUC",location:"Champaign, IL",domain:"illinois.edu"},
{rank:39,id:"bowdoin",cdId:"bowdoin",name:"Bowdoin College",short:"Bowdoin",location:"Brunswick, ME",domain:"bowdoin.edu"},
{rank:40,id:"byu",cdId:"brigham-young-university",name:"Brigham Young University",short:"BYU",location:"Provo, UT",domain:"byu.edu"},
{rank:41,id:"georgetown",cdId:"georgetown",name:"Georgetown University",short:"Georgetown",location:"Washington, DC",domain:"georgetown.edu"},
{rank:42,id:"ucsb",cdId:"uc-santa-barbara",name:"University of California, Santa Barbara",short:"UC Santa Barbara",location:"Santa Barbara, CA",domain:"ucsb.edu"},
{rank:43,id:"cmu",cdId:"carnegie-mellon",name:"Carnegie Mellon University",short:"Carnegie Mellon",location:"Pittsburgh, PA",domain:"cmu.edu"},
{rank:44,id:"uc-davis",cdId:"uc-davis",name:"University of California, Davis",short:"UC Davis",location:"Davis, CA",domain:"ucdavis.edu"},
{rank:45,id:"boston-university",cdId:"boston-university",name:"Boston University",short:"Boston University",location:"Boston, MA",domain:"bu.edu"},
{rank:46,id:"ut-austin",cdId:"university-of-texas-at-austin",name:"University of Texas at Austin",short:"UT Austin",location:"Austin, TX",domain:"utexas.edu"},
{rank:47,id:"washington-lee",cdId:"washington-and-lee-university",name:"Washington and Lee University",short:"Washington and Lee",location:"Lexington, VA",domain:"wlu.edu"},
{rank:48,id:"colgate",cdId:"colgate-university",name:"Colgate University",short:"Colgate",location:"Hamilton, NY",domain:"colgate.edu"},
{rank:49,id:"nyu",cdId:"new-york-university",name:"New York University",short:"NYU",location:"New York, NY",domain:"nyu.edu"},
{rank:50,id:"uw-seattle",cdId:"university-of-washington",name:"University of Washington, Seattle",short:"Washington",location:"Seattle, WA",domain:"washington.edu"},
{rank:51,id:"wesleyan",cdId:"wesleyan-university",name:"Wesleyan University",short:"Wesleyan",location:"Middletown, CT",domain:"wesleyan.edu"},
{rank:52,id:"middlebury",cdId:"middlebury-college",name:"Middlebury College",short:"Middlebury",location:"Middlebury, VT",domain:"middlebury.edu"},
{rank:53,id:"wisconsin",cdId:"university-of-wisconsin-madison",name:"University of Wisconsin–Madison",short:"Wisconsin",location:"Madison, WI",domain:"wisc.edu"},
{rank:54,id:"boston-college",cdId:"boston-college",name:"Boston College",short:"Boston College",location:"Chestnut Hill, MA",domain:"bc.edu"},
{rank:55,id:"cal-poly",cdId:"california-polytechnic-state-university-san-luis-obispo",name:"California Polytechnic State University, San Luis Obispo",short:"Cal Poly",location:"San Luis Obispo, CA",domain:"calpoly.edu"},
{rank:56,id:"haverford",cdId:"haverford-college",name:"Haverford College",short:"Haverford",location:"Haverford, PA",domain:"haverford.edu"},
{rank:57,id:"uga",cdId:"university-of-georgia",name:"University of Georgia",short:"Georgia",location:"Athens, GA",domain:"uga.edu"},
{rank:58,id:"tufts",cdId:"tufts",name:"Tufts University",short:"Tufts",location:"Medford, MA",domain:"tufts.edu"},
{rank:59,id:"davidson",cdId:"davidson-college",name:"Davidson College",short:"Davidson",location:"Davidson, NC",domain:"davidson.edu"},
{rank:60,id:"william-mary",cdId:"william-and-mary",name:"William & Mary",short:"William & Mary",location:"Williamsburg, VA",domain:"wm.edu"},
{rank:61,id:"texas-am",cdId:"texas-am-university",name:"Texas A&M University, College Station",short:"Texas A&M",location:"College Station, TX",domain:"tamu.edu"},
{rank:62,id:"purdue",cdId:"purdue-university",name:"Purdue University",short:"Purdue",location:"West Lafayette, IN",domain:"purdue.edu"},
{rank:63,id:"ucsc",cdId:"university-of-california-santa-cruz",name:"University of California, Santa Cruz",short:"UC Santa Cruz",location:"Santa Cruz, CA",domain:"ucsc.edu"},
{rank:64,id:"lehigh",cdId:"lehigh-university",name:"Lehigh University",short:"Lehigh",location:"Bethlehem, PA",domain:"lehigh.edu"},
{rank:65,id:"santa-clara",cdId:"santa-clara-university",name:"Santa Clara University",short:"Santa Clara",location:"Santa Clara, CA",domain:"scu.edu"},
{rank:66,id:"nc-state",cdId:"north-carolina-state-university",name:"North Carolina State University, Raleigh",short:"NC State",location:"Raleigh, NC",domain:"ncsu.edu"},
{rank:67,id:"gwu",cdId:"gwu",name:"George Washington University",short:"GWU",location:"Washington, DC",domain:"gwu.edu"},
{rank:68,id:"binghamton",cdId:"binghamton-university",name:"Binghamton University, SUNY",short:"Binghamton",location:"Vestal, NY",domain:"binghamton.edu"},
{rank:69,id:"rochester",cdId:"university-of-rochester",name:"University of Rochester",short:"Rochester",location:"Rochester, NY",domain:"rochester.edu"},
{rank:70,id:"rutgers",cdId:"rutgers-university-new-brunswick",name:"Rutgers University–New Brunswick",short:"Rutgers",location:"New Brunswick, NJ",domain:"rutgers.edu"},
{rank:71,id:"colby",cdId:"colby-college",name:"Colby College",short:"Colby",location:"Waterville, ME",domain:"colby.edu"},
{rank:72,id:"fsu",cdId:"florida-state-university",name:"Florida State University",short:"Florida State",location:"Tallahassee, FL",domain:"fsu.edu"},
{rank:73,id:"hamilton",cdId:"hamilton-college",name:"Hamilton College",short:"Hamilton",location:"Clinton, NY",domain:"hamilton.edu"},
{rank:74,id:"holy-cross",cdId:"college-of-the-holy-cross",name:"College of the Holy Cross",short:"Holy Cross",location:"Worcester, MA",domain:"holycross.edu"},
{rank:75,id:"villanova",cdId:"villanova-university",name:"Villanova University",short:"Villanova",location:"Villanova, PA",domain:"villanova.edu"},
{rank:76,id:"miami",cdId:"university-of-miami",name:"University of Miami",short:"Miami",location:"Coral Gables, FL",domain:"miami.edu"},
{rank:77,id:"ucr",cdId:"university-of-california-riverside",name:"University of California, Riverside",short:"UC Riverside",location:"Riverside, CA",domain:"ucr.edu"},
{rank:78,id:"minnesota",cdId:"university-of-minnesota-twin-cities",name:"University of Minnesota, Twin Cities",short:"Minnesota",location:"Minneapolis, MN",domain:"umn.edu"},
{rank:79,id:"michigan-state",cdId:"michigan-state-university",name:"Michigan State University",short:"Michigan State",location:"East Lansing, MI",domain:"msu.edu"},
{rank:80,id:"stony-brook",cdId:"stony-brook-university",name:"Stony Brook University, SUNY",short:"Stony Brook",location:"Stony Brook, NY",domain:"stonybrook.edu"},
{rank:81,id:"virginia-tech",cdId:"virginia-tech",name:"Virginia Tech",short:"Virginia Tech",location:"Blacksburg, VA",domain:"vt.edu"},
{rank:82,id:"trinity-tx",cdId:"trinity-university",name:"Trinity University",short:"Trinity",location:"San Antonio, TX",domain:"trinity.edu"},
{rank:83,id:"ohio-state",cdId:"ohio-state-university",name:"Ohio State University",short:"Ohio State",location:"Columbus, OH",domain:"osu.edu"},
{rank:84,id:"harvey-mudd",cdId:"harvey-mudd-college",name:"Harvey Mudd College",short:"Harvey Mudd",location:"Claremont, CA",domain:"hmc.edu"},
{rank:85,id:"bucknell",cdId:"bucknell-university",name:"Bucknell University",short:"Bucknell",location:"Lewisburg, PA",domain:"bucknell.edu"},
{rank:86,id:"clemson",cdId:"clemson-university",name:"Clemson University",short:"Clemson",location:"Clemson, SC",domain:"clemson.edu"},
{rank:87,id:"sdsu",cdId:"san-diego-state-university",name:"San Diego State University",short:"San Diego State",location:"San Diego, CA",domain:"sdsu.edu"},
{rank:88,id:"trinity-ct",cdId:"trinity-college",name:"Trinity College",short:"Trinity College",location:"Hartford, CT",domain:"trincoll.edu"},
{rank:89,id:"smith",cdId:"smith-college",name:"Smith College",short:"Smith",location:"Northampton, MA",domain:"smith.edu"},
{rank:90,id:"baruch",cdId:"baruch-college",name:"CUNY, Baruch College",short:"Baruch",location:"New York, NY",domain:"baruch.cuny.edu"},
{rank:91,id:"lafayette",cdId:"lafayette-college",name:"Lafayette College",short:"Lafayette",location:"Easton, PA",domain:"lafayette.edu"},
{rank:92,id:"richmond",cdId:"university-of-richmond",name:"University of Richmond",short:"Richmond",location:"Richmond, VA",domain:"richmond.edu"},
{rank:93,id:"colorado",cdId:"colorado",name:"University of Colorado Boulder",short:"Colorado",location:"Boulder, CO",domain:"colorado.edu"},
{rank:94,id:"indiana",cdId:"indiana-university-bloomington",name:"Indiana University Bloomington",short:"Indiana",location:"Bloomington, IN",domain:"indiana.edu"},
{rank:95,id:"babson",cdId:"babson-college",name:"Babson College",short:"Babson",location:"Wellesley, MA",domain:"babson.edu"},
{rank:96,id:"oklahoma",cdId:"university-of-oklahoma",name:"University of Oklahoma, Norman",short:"Oklahoma",location:"Norman, OK",domain:"ou.edu"},
{rank:97,id:"csulb",cdId:"california-state-university-long-beach",name:"California State University, Long Beach",short:"Cal State Long Beach",location:"Long Beach, CA",domain:"csulb.edu"},
{rank:98,id:"wake-forest",cdId:"wake-forest-university",name:"Wake Forest University",short:"Wake Forest",location:"Winston-Salem, NC",domain:"wfu.edu"},
{rank:99,id:"utah",cdId:"university-of-utah",name:"University of Utah",short:"Utah",location:"Salt Lake City, UT",domain:"utah.edu"},
{rank:100,id:"bates",cdId:"bates-college",name:"Bates College",short:"Bates",location:"Lewiston, ME",domain:"bates.edu"}
];